# Generated by Django 5.2.2 on 2025-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='channel_name')),
                ('channel_id', models.IntegerField(max_length=255, unique=True, verbose_name='channel_id')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='channel_status')),
                ('last_message_id', models.IntegerField(blank=True, max_length=255, null=True, unique=True, verbose_name='last_message_id')),
            ],
        ),
    ]
