# Generated by Django 5.2.7 on 2025-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.IntegerField(default=0, null=True, verbose_name='channel_id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='last_message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='last_message_id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(default='active', max_length=10, verbose_name='channel_status'),
        ),
    ]
