# Generated by Django 5.2.1 on 2025-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='channel_id')),
                ('channel_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='channel_username')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='post')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='company')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='salary')),
                ('busyness', models.CharField(blank=True, max_length=255, null=True, verbose_name='busyness')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='vacancy_name')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='company')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='salary')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='phone')),
                ('busyness', models.CharField(blank=True, max_length=25, null=True, verbose_name='busyness')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
