# Generated by Django 5.2.2 on 2025-06-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channels',
        ),
    ]
