# Generated by Django 5.2.1 on 2025-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=255, null=True, verbose_name='word')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='vacancy_name')),
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='salary')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='phone')),
            ],
            options={
                'verbose_name': '=Vacation=',
                'verbose_name_plural': '=Vacation=',
            },
        ),
    ]
