# Generated by Django 5.2.7 on 2025-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0002_delete_channels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='busyness',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='post',
        ),
        migrations.AddField(
            model_name='keyword',
            name='address',
            field=models.JSONField(blank=True, default=list, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='description',
            field=models.JSONField(blank=True, default=list, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='experience',
            field=models.JSONField(blank=True, default=list, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='schedule'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='title',
            field=models.JSONField(blank=True, default=list, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='work_format',
            field=models.JSONField(blank=True, default=list, verbose_name='work_format'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='city',
            field=models.JSONField(blank=True, default=list, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='company',
            field=models.JSONField(blank=True, default=list, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='salary',
            field=models.JSONField(blank=True, default=list, verbose_name='salary'),
        ),
    ]
