# Generated by Django 5.2.7 on 2025-11-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HeadHunter', 'HeadHunter'), ('SuperJob', 'SuperJob'), ('Telegram', 'Telegram')])),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='building',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='hh_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='street',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='work_schedule_by_days',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='education',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='platform_vacancy_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contacts',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='hh_parser.city'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='hh_parser.company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='hh_parser.platform'),
        ),
    ]
