# Generated by Django 5.2.2 on 2025-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superjob_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superjob',
            name='salary',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
