# Generated by Django 5.2.2 on 2025-06-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superjob_parser', '0002_alter_superjob_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superjob',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
